metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets:
      - "container" # collects information and statistics about running Docker containers (container labels, name, status
      - "cpu" # collects runtime CPU metrics
      - "diskio"
      - "healthcheck"
      - "info"
      #- "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true
  - module: prometheus
    period: 10s
    enabled: true
    hosts: ["prometheus:9090"]
    metrics_path: '/federate'
    query:
      'match[]': '{__name__!=""}'

#processors:
#  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup:
  dashboards.enabled: true
  kibana:
    host: 'kibana:5601'