version: '3.4'

x-fluentd-logging:
  &custom-logging
  logging:
    driver: fluentd
    options:
      fluentd-address: localhost:24224
      tag: docker.{{.Name}}

services:

  ##### IoT Sensors #####
  simplesensor:
    image: danielfuvesi/bigdataincidentanalytics:simplesensor
    networks:
      - iot-big-data
    volumes:
      - ./sensors/simplesensor:/var/config
    command: npm start -- -c /var/config/config.json
    << : *custom-logging

  ##### MQTT Broker #####
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    domainname: iot-big-data
    networks:
      - iot-big-data
    ports:
      - 1883:1883
      - 9001:9001
    << : *custom-logging

  ##### FLINK #####
  flink_jobmanager:
    build: ./flink
    container_name: jobmanager
    expose:
      - 6123
      - 9249
    ports:
      - 8081:8081
    networks:
      - iot-big-data
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    << : *custom-logging

  flink_taskmanager:
    build: ./flink
    expose:
      - 6121
      - 6122
      - 9249
    networks:
      - iot-big-data
    depends_on:
      - flink_jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLUENTD_TAG_PREFIX=flink-processing
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    << : *custom-logging

  ##### NIFI #####
  nifi:
    build: ./nifi
    hostname: nifi
    container_name: nifi
    volumes:
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./hadoop/config:/opt/nifi/nifi-current/hadoop
    networks:
      - iot-big-data
    ports:
      - 8080:8080
    << : *custom-logging

  ##### HADOOP #####
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    expose:
      - 8020
    networks:
      - iot-big-data
    volumes:
      - /hadoop/dfs/name
      - ./hadoop/hadoop_setup.sh:/usr/local/bin/hadoop_setup.sh
    command: hadoop_setup.sh
    environment:
      - CLUSTER_NAME=myCluster
    ports:
      - 50070:50070
    << : *custom-logging

  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    networks:
      - iot-big-data
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_permissions=false
    << : *custom-logging

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    networks:
      - iot-big-data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
      - HDFS_CONF_dfs_permissions=false
    ports:
      - 8088:8088
    << : *custom-logging

  nodemanager1:
    image: uhopper/hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    networks:
      - iot-big-data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - HDFS_CONF_dfs_permissions=false
    << : *custom-logging

  ##### Node-RED #####
  nodered:
    image: nodered/node-red-docker:slim
    ports:
      - 1880:1880
    networks:
      - iot-big-data
    volumes:
      - ./nodered:/data
    << : *custom-logging

  ##### ELK Stack #####
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - iot-big-data

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - iot-big-data
    depends_on:
      - elasticsearch

  # THIS SERVICE IS DEFINED JUST FOR COMPLETENESS. FLUENTD *MUST* BE STARTED ON HOST BEFORE ANY OTHER SERVICE,
  # OTHERWISE THE OTHER CONTAINERS CAN'T START DUE TO MISSING LOGGING DRIVER.
  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log/bigdataincidentanalytics
    networks:
      - iot-big-data
    ports:
      - 24224:24224
      - 24224:24224/udp
      - 9880:9880

  # Just for showcasing different situations regarding monitoring and reasoning
  neo4j:
    build:
      context: neo4j/
      args:
        CYPHER_FILE: database.cypher
    container_name: neo4j
    restart: always
    networks:
      - iot-big-data
    volumes:
      - ./neo4j/data:/logs
    ports:
      - 7474:7474
      - 7687:7687

networks:
  iot-big-data:
    driver: bridge