version: '3.4'

x-fluentd-logging:
  &custom-logging
  logging:
    driver: fluentd
    options:
      fluentd-address: localhost:24224
      tag: docker.{{.Name}}
      fluentd-sub-second-precision: "true"

services:

  ##### IoT SENSORS #####
  simplesensor:
    image: simplesensor-usv:latest
    networks:
      - iot-big-data
      - pipeline
    volumes:
      - ./pipeline/sensors/simplesensor:/var/config
      - $ETC_LOCALTIME:/etc/localtime:ro
    environment:
      - FLUENTD_TAG=com.rdsea.sensor
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
      - RATE_MS=1000
    command: npm start -- -c /var/config/config.json
    << : *custom-logging

  ##### MQTT BROKER #####
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    domainname: iot-big-data
    networks:
      - iot-big-data
      - pipeline
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./pipeline/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./pipeline/mqtt/mosquitto.log:/var/log/mosquitto.log
      - $ETC_LOCALTIME:/etc/localtime:ro
    << : *custom-logging

  mqtt_fluentbit:
    image: fluent/fluent-bit:1.0.6
    volumes:
      - ./pipeline/mqtt/mosquitto.log:/fluent-bit/etc/log/mqtt.log
      - ./pipeline/mqtt/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./pipeline/mqtt/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data

  ##### APACHE FLINK #####
  flink_jobmanager:
    build: pipeline/flink
    container_name: jobmanager
    expose:
      - 6123
      - 9249
    ports:
      - 8081:8081
    volumes:
      - ./pipeline/flink/logback.xml:/opt/flink/conf/logback-console.xml:ro
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data
      - pipeline
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - LOG_COMPONENT_TAG=com.rdsea.flink.platform.jobmanager

  flink_taskmanager:
    build: pipeline/flink
    expose:
      - 6121
      - 6122
      - 9249
    volumes:
      - ./pipeline/flink/logback.xml:/opt/flink/conf/logback-console.xml:ro
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data
      - pipeline
    depends_on:
      - flink_jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLUENTD_TAG_PREFIX=com.rdsea.flink-processing
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
      - LOG_COMPONENT_TAG=com.rdsea.flink.platform.taskmanager

  ##### APACHE NIFI #####
  nifi:
    build: pipeline/nifi
    hostname: nifi
    container_name: nifi
    volumes:
      - ./pipeline/nifi/logs:/opt/nifi/nifi-current/logs
      - ./pipeline/hadoop/config:/opt/nifi/nifi-current/hadoop
      - ./pipeline/nifi/logback.xml:/opt/nifi/nifi-current/conf/logback.xml:ro
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data
      - pipeline
    ports:
      - 8080:8080
    expose:
      - 9092
    environment:
      - LOG_COMPONENT_TAG=com.rdsea.nifi.platform

  ##### APACHE HADOOP #####
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    expose:
      - 8020
    networks:
      - iot-big-data
      - pipeline
    volumes:
      - /hadoop/dfs/name
      - ./pipeline/hadoop/hadoop_setup.sh:/usr/local/bin/hadoop_setup.sh
      - $ETC_LOCALTIME:/etc/localtime:ro
    command: hadoop_setup.sh
    environment:
      - CLUSTER_NAME=myCluster
    ports:
      - 50070:50070
    << : *custom-logging

  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    networks:
      - iot-big-data
      - pipeline
    volumes:
      - /hadoop/dfs/data
      - $ETC_LOCALTIME:/etc/localtime:ro
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_permissions=false
    << : *custom-logging

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    networks:
      - iot-big-data
      - pipeline
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
      - HDFS_CONF_dfs_permissions=false
    ports:
      - 8088:8088
    volumes:
      - $ETC_LOCALTIME:/etc/localtime:ro
    << : *custom-logging

  nodemanager1:
    image: uhopper/hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    networks:
      - iot-big-data
      - pipeline
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - HDFS_CONF_dfs_permissions=false
    volumes:
      - $ETC_LOCALTIME:/etc/localtime:ro
    << : *custom-logging

  ##### Node-RED #####
  nodered:
    build: pipeline/nodered
    ports:
      - 1880:1880
    networks:
      - iot-big-data
      - pipeline
    volumes:
      - ./pipeline/nodered/data:/data
      - $ETC_LOCALTIME:/etc/localtime:ro
    environment:
      - FLUENTD_TAG_PREFIX=com.rdsea.nodered
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224

  ##### APACHE SPARK #####
  spark-master:
    build: pipeline/spark/master
    container_name: spark-master
    ports:
      - 8083:8080
    expose:
      - 7077
    environment:
      - ENABLE_INIT_DAEMON=false
      - "constraint:node==master"
      - LOG_COMPONENT_TAG=com.rdsea.spark.platform.master
    volumes:
      - ./pipeline/hadoop/config/core-site.xml:/etc/hadoop/core-site.xml
      - ./pipeline/hadoop/config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./pipeline/spark/config/spark-env.sh:/spark/conf/spark-env.sh
      - ./pipeline/spark/master/logback.xml:/spark/conf/logback.xml:ro
      - ./pipeline/spark/master/metrics.properties:/spark/conf/metrics.properties
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data
      - pipeline

  spark-worker:
    build: pipeline/spark/worker
    depends_on:
      - spark-master
    ports:
      - 8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - ENABLE_INIT_DAEMON=false
      - "constraint:node==master"
      - LOG_COMPONENT_TAG=com.rdsea.spark.platform.worker
    volumes:
      - ./pipeline/hadoop/config/core-site.xml:/etc/hadoop/core-site.xml
      - ./pipeline/hadoop/config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./pipeline/spark/config/spark-env.sh:/spark/conf/spark-env.sh
      - ./pipeline/spark/worker/logback.xml:/spark/conf/logback.xml:ro
      - ./pipeline/spark/worker/metrics.properties:/spark/conf/metrics.properties
      - $ETC_LOCALTIME:/etc/localtime:ro
    networks:
      - iot-big-data
      - pipeline

  spark-app:
    build: pipeline/spark/iot-big-data-spark
    container_name: spark-app
    ports:
      - 4040
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - ENABLE_INIT_DAEMON=false
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - FLUENTD_TAG_PREFIX=com.rdsea.spark-kmeans
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
      - HDFS_URL=hdfs://namenode:8020/nifi
      - LOG_COMPONENT_TAG=com.rdsea.spark.platform.kmeans
    volumes:
      - $ETC_LOCALTIME:/etc/localtime:ro
      - ./pipeline/spark/iot-big-data-spark/logback.xml:/spark/conf/logback.xml:ro
      - ./pipeline/spark/iot-big-data-spark/metrics.properties:/spark/conf/metrics.properties
      - ./pipeline/spark/iot-big-data-spark/predictions:/spark/data/predictions
      - ./pipeline/spark/iot-big-data-spark/kmeans_sensors.py:/app/app.py
    networks:
      - iot-big-data
      - pipeline

networks:
  iot-big-data:
    driver: bridge
  pipeline:
    driver: bridge