version: '2.4'

services:

  ##### IoT Sensors #####
  simplesensor:
    image: danielfuvesi/bigdataincidentanalytics:simplesensor
    networks:
      - iot-big-data
    volumes:
      - ./sensors/simplesensor:/var/config
    command: npm start -- -c /var/config/config.json

  ##### MQTT Broker #####
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    domainname: iot-big-data
    networks:
      - iot-big-data
    ports:
      - 1883:1883
      - 9001:9001

  ##### PROMETHEUS MOSQUITTO EXPORTER
  mqtt_exporter:
    image: sapcc/mosquitto-exporter:0.5.0
    container_name: mosquitto-exporter
    networks:
      - iot-big-data
    ports:
      - 9234:9234
    environment:
      - BROKER_ENDPOINT=tcp://mqtt:1883
    depends_on:
      - mqtt

  ##### FLINK #####
  flink_jobmanager:
    build: ./flink
    container_name: jobmanager
    expose:
      - 6123
      - 9249
    ports:
      - 8081:8081
    networks:
      - iot-big-data
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  flink_taskmanager:
    build: ./flink
    expose:
      - 6121
      - 6122
      - 9249
    networks:
      - iot-big-data
    depends_on:
      - flink_jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  ##### NIFI #####
  nifi:
    build: ./nifi
    hostname: nifi
    container_name: nifi
    volumes:
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./hadoop/config:/opt/nifi/nifi-current/hadoop
    networks:
      - iot-big-data
    ports:
      - 8080:8080

  ##### HADOOP #####
  namenode:
    image: uhopper/hadoop-namenode
    hostname: namenode
    container_name: namenode
    expose:
      - 8020
    networks:
      - iot-big-data
    volumes:
      - /hadoop/dfs/name
      - ./hadoop/hadoop_setup.sh:/usr/local/bin/hadoop_setup.sh
    command: hadoop_setup.sh
    environment:
      - CLUSTER_NAME=myCluster
    ports:
      - 50070:50070

  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    networks:
      - iot-big-data
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_permissions=false

  resourcemanager:
    image: uhopper/hadoop-resourcemanager
    hostname: resourcemanager
    container_name: resourcemanager
    networks:
      - iot-big-data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
      - HDFS_CONF_dfs_permissions=false
    ports:
      - 8088:8088

  nodemanager1:
    image: uhopper/hadoop-nodemanager
    hostname: nodemanager1
    container_name: nodemanager1
    networks:
      - iot-big-data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - HDFS_CONF_dfs_permissions=false

  ##### Node-RED #####
  nodered:
    image: nodered/node-red-docker:slim
    ports:
      - 1880:1880
    networks:
      - iot-big-data
    volumes:
      - ./nodered:/data

  ##### ELK Stack #####
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      - iot-big-data

  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.2
    container_name: elasticsearch-exporter
    command: -es.uri=http://elasticsearch:9200
    restart: always
    ports:
      - 9108:9108
    networks:
      - elk
      - iot-big-data
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - elk
      - iot-big-data
    depends_on:
      - elasticsearch

  ##### PROMETHEUS #####
  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - iot-big-data
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - iot-big-data

  ##### GRAFANA #####
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - iot-big-data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/

networks:
  iot-big-data:
    driver: bridge
  elk:
    driver: bridge