version: '3.4'

services:

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/targets.json:/etc/prometheus/targets.json
      - ./monitoring/prometheus/rules/:/etc/prometheus/rules/
    command: "--web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml"
    networks:
      - iot-big-data

  # PROMETHEUS "PUSH" CAPABILITY
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - iot-big-data

  # PROMETHEUS ALERT MANAGER
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./monitoring/prometheus/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'
    networks:
      - iot-big-data

  # MOSQUITTO PROMETHEUS EXPORTER
  mqtt_exporter:
    image: sapcc/mosquitto-exporter:0.5.0
    container_name: mosquitto-exporter
    restart: always
    networks:
      - iot-big-data
    ports:
      - 9234:9234
    environment:
      - BROKER_ENDPOINT=tcp://mqtt:1883

  # HADOOP NAMENODE PROMETHEUS EXPORTER
  namenode_exporter:
    image: danielfuvesi/bigdataincidentanalytics:hadoop-namenode-exporter
    container_name: hadoop-namenode-exporter
    restart: always
    networks:
      - iot-big-data
    command: -namenode.jmx.url "http://namenode:50070/jmx"
    expose:
      - 9070

  # HADOOP RESOURCEMANAGER PROMETHEUS EXPORTER
  resourcemanager_exporter:
    image: danielfuvesi/bigdataincidentanalytics:hadoop-resourcemanager-exporter
    container_name: hadoop-resourcemanager-exporter
    networks:
      - iot-big-data
    command: -resourcemanager.url "http://resourcemanager:8088"
    expose:
      - 9088

  # ELASTICSEARCH PROMETHEUS EXPORTER
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.2
    container_name: elasticsearch-exporter
    command: -es.uri=http://elasticsearch:9200
    restart: always
    expose:
      - 9108
    networks:
      - iot-big-data

  # BRIDGE TO BRING SPARK JVM METRICS INTO PROMETHEUS
  graphite_exporter:
    image: prom/graphite-exporter
    command: "--graphite.mapping-config=/tmp/graphite_mapping.conf"
    container_name: graphite_exporter
    volumes:
      - ./monitoring/prometheus/graphite_mapping.conf:/tmp/graphite_mapping.conf
    expose:
      - 9108
      - 9109
      - 9109/udp
    networks:
      - iot-big-data

  # OPTIONAL: GRAFANA FOR VISUALIZING PROMETHEUS METRICS WITH DASHBOARDS
  grafana:
    image: grafana/grafana:6.4.0
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - iot-big-data
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/

networks:
  iot-big-data:
    driver: bridge