{
 "title": "Docker Dashboard",
 "description": "Docker Monitoring Template",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_total_bytes) - sum(node_memory_free_bytes) ) / sum(node_memory_total_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/docker\"}[1m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\",name!~\"kibana|fluentd|cadvisor|prometheus|grafana|pushgateway|mosquitto-exporter|elasticsearch-exporter\"}[1m])) by (container_label_com_docker_compose_service))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",name!~\"kibana|fluentd|cadvisor|prometheus|grafana|pushgateway|mosquitto-exporter|elasticsearch-exporter\"}) by (container_label_com_docker_compose_service))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (container_label_com_docker_compose_service) (rate(container_network_receive_bytes_total{image!=\"\",name!~\"kibana|fluentd|cadvisor|prometheus|grafana|pushgateway|mosquitto-exporter|elasticsearch-exporter\"}[1m] ) ))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (container_label_com_docker_compose_service) (rate(container_network_transmit_bytes_total{image!=\"\",name!~\"kibana|fluentd|cadvisor|prometheus|grafana|pushgateway|mosquitto-exporter|elasticsearch-exporter\"}[1m] ) ))",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  }
 ]
}