{
 "title": "Nifi",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Heap Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_heap_stats{job=\"jvm_global\",instance=\"nifi\",status=\"usage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads State Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_thread_stats{instance=\"nifi\",status=~\"state_timed_waiting|state_runnable|state_waiting|state_blocked\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of FlowFiles in ProcessGroup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_group_amount_flowfiles_total{job=\"nifi_reporting_job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of Bytes in ProcessGroup",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_group_amount_bytes_total{job=\"nifi_reporting_job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}