{
 "title": "Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Socket Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "broker_load_sockets_1min", "legendFormat": "MQTT" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"mosquitto\"})",
     "legendFormat": "MQTT process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"mosquitto\"}",
     "legendFormat": "MQTT VM"
    }
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_corruptions_total{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"mosquitto\"})",
     "legendFormat": "MQTT open_fds"
    }
   ]
  },
  {
   "title": "Bytes Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "broker_load_bytes_received_1min",
     "legendFormat": "Received"
    },
    { "expr": "broker_load_bytes_sent_1min", "legendFormat": "Sent" }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "broker_load_messages_received_1min",
     "legendFormat": "Received"
    },
    { "expr": "broker_load_messages_sent_1min", "legendFormat": "Sent" }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=\"prometheus\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"prometheus\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=\"prometheus\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=\"prometheus\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=\"prometheus\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "broker_clients_connected", "legendFormat": "MQTT" }
   ]
  },
  {
   "title": "Publish Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "broker_publish_messages_sent", "legendFormat": "Sent" },
    {
     "expr": "broker_publish_messages_dropped",
     "legendFormat": "Dropped"
    }
   ]
  }
 ]
}