groups:
- name: MQTT_BROKER
  rules:
  - alert: MqttInstanceDownAlert
    expr: increase(broker_uptime{job="mqtt"}[30s]) == 0
    labels:
      severity: critical
      pipeline_component: MQTT_BROKER
    annotations:
      summary: "MQTT not reachable"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has not been receiving any increase in the broker's uptime for half a minute."