apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mosquitto
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
          ports:
            - containerPort: 9001
            - containerPort: 1883