global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: 'dummy'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - targets.json
        refresh_interval: 1m
#
#  - job_name: 'elasticsearch'
#    static_configs:
#      - targets: ['elasticsearch-exporter:9108']
#
#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080
