global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mqtt'
    static_configs:
      - targets: ['mosquitto-exporter:9234']

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:9249']

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['bigdataincidentanalytics_flink_taskmanager_1:9249']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9108']

  - job_name: 'nifi'
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: 'hadoop-namenode'
    scrape_interval: 5s
    static_configs:
      - targets:
          - hadoop-namenode-exporter:9070

  - job_name: 'hadoop-resourcemanager'
    scrape_interval: 5s
    static_configs:
      - targets:
          - hadoop-resourcemanager-exporter:9088