global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - "./rules/mqtt.yml"
  - "./rules/nodered.yml"

# The targets are moved to a separate 'targets.json' file on purpose.
# With file_sd_configs Prometheus can watch the file for changes, this means we can
# dynamically update the targets without needing to restart Prometheus.
scrape_configs:
  - job_name: 'dummy'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - targets.json
        refresh_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']