apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: kube-system
spec:
  selector:
    k8s-app: fluentd-gcp-custom
  ports:
    - name: http
      protocol: TCP
      port: 9880
      targetPort: 9880
    - name: forward
      protocol: TCP
      port: 24224
      targetPort: 24224
  type: LoadBalancer